# ARTIE manager parameters
manager:
    number_of_threads:  8
    number_of_runs:     2
    number_of_events:   32
    seed:               10942
    mode:               "run"   # interactive/run
    output_filename:    "blip_test"
    save_particle_maps: true
    save_primary_info:  true

# ARTIE argon parameters 
argon:
    use_g4_definition:  false
    argon_36_ratio:     0.334   # %
    argon_38_ratio:     0.063   # %
    argon_40_ratio:     99.603  # %
    lar_density:        1.3954  # g/cm^3
    lar_temperature:    85.0    # K
    lar_pressure:       0.952   # atm

hall:
    world_x: 20    # m                 
    world_y: 20    # m
    world_z: 60    # m
    world_material: "high_vacuum"
    argon_x: 7 
    argon_y: 7 
    argon_z: 7 
    
# BoxRadGenerator parameters
generator:
    start_time_ns:      -250000     # 250 us, before the trigger
    end_time_ns:        2750000     # 2.75 ms, post trigger
    radiological:       "Argon_39"
    rateInBqPerCC:      0.00141
    overrideNDecays:    false
    nDecays:            100
    spectrumPath:       "/home/rivera/Documents/Code/Blips/BlipSim/spectra/"
    energy:             500
